spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dongjianOne/spring-cloud-config-server.git
          search-paths: src/main/java/com/yml/ #git地址下的相对地址，可以配置多个，用，隔开
          username: dongjianOne
          password: dj975573.

#          rabbitmq
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 8001
  # spring.profiles.active=native
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    ## 注册中心eureka地址
#关闭安全验证（默认为true)
management:
  security:
    enabled: false
